# Generated by Django 5.1.3 on 2024-12-07 08:20

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESRBRating',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=32)),
                ('name_ru', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='static/icons')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('background_image', models.ImageField(default='default.svg', upload_to='media')),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.ForeignKey(default=games.models.ESRBRating.get_default_rating, on_delete=django.db.models.deletion.SET_DEFAULT, to='games.esrbrating')),
                ('genres', models.ManyToManyField(to='games.genre')),
                ('platforms', models.ManyToManyField(to='games.platform')),
                ('tags', models.ManyToManyField(to='games.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
        ),
    ]
