# Generated by Django 5.1.3 on 2024-12-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESRBRating',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=32)),
                ('name_ru', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='static/icons')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='static/icons')),
            ],
        ),
    ]
