# Generated by Django 5.1.3 on 2024-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESRBRating',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=32)),
                ('name_ru', models.CharField(max_length=32)),
            ],
        ),
    ]
