# Generated by Django 5.1.3 on 2024-12-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrbrating',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
