# Generated by Django 5.1.3 on 2024-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_developer_rename_rating_game_esrb_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='minimal',
            new_name='minimum',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(to='games.screenshot'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
