# Generated by Django 5.1.3 on 2024-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_minimal_requirement_minimum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='background_image',
            field=models.URLField(),
        ),
    ]
