# Generated by Django 5.1.3 on 2024-12-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='price_in_cent',
            new_name='price_in_cents',
        ),
    ]
