# Generated by Django 5.1.3 on 2024-12-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_price_in_cent_game_price_in_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrbrating',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
