# Generated by Django 5.1.3 on 2024-12-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_esrbrating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrbrating',
            name='image',
            field=models.ImageField(upload_to='static/icons'),
        ),
    ]
