# Generated by Django 5.1.3 on 2025-01-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_esrbrating_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrbrating',
            name='minimum_age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
