# Generated by Django 5.1.3 on 2025-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_esrbrating_minimum_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrbrating',
            name='minimum_age',
            field=models.PositiveIntegerField(),
        ),
    ]
