# Generated by Django 5.1.3 on 2024-12-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('numeric_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=64)),
                ('currency_symbol', models.CharField(max_length=6)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='currency.currencyrate')),
            ],
        ),
    ]
