# Generated by Django 5.1.3 on 2024-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(max_length=6),
        ),
    ]
