# Generated by Django 5.1.3 on 2024-12-03 10:14

import currency.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=currency.models.Country.get_default_country, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='currency.country'),
        ),
    ]
