# Generated by Django 5.1.3 on 2024-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
