# Generated by Django 5.1.3 on 2024-12-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_day',
            new_name='birthdate',
        ),
    ]
