# Generated by Django 5.1.3 on 2024-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_birth_day_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar.png', upload_to='static/img'),
        ),
    ]
