# Generated by Django 5.1.3 on 2025-01-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/icons/default-avatar.png', upload_to='static/img'),
        ),
    ]
