# Generated by Django 5.1.3 on 2025-01-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_confirmationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPasswordCode',
        ),
    ]
