# Generated by Django 5.1.3 on 2025-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_status_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
    ]
